---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-list-pods
  namespace: prometheus
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
roleRef:
  kind: ClusterRole
  name: read-all-pods
  apiGroup: rbac.authorization.k8s.io
